node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Update GIT') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email gopim4959@gmail.com"
                        sh "git config user.name gmanne11"
                        //sh "git switch master"
                        sh "cat kubernetesmanifest-GitOps/deployment.yaml"
                        sh "sed -i 's+vivekmanne/gitops-demo.*+vivekmanne/gitops-demo:${DOCKERTAG}+g' kubernetesmanifest-GitOps/deployment.yaml"
                        sh "cat kubernetesmanifest-GitOps/deployment.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/gmanne11/AWS-Cloud-projects.git HEAD:main"
      }
    }
  }
}
}